---
title: "pie_map_ch2"
author: "Anita Wray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
## Load packages
library("tidyverse")
theme_set(theme_bw())
library("sf")
library("ggspatial")
library('viridis')
library('rnaturalearth')
library('diveRsity')
library('patchwork')
library('maps')
library(scatterpie)
library(plotly)

## Set WD and subset data for species specific graphs
setwd('C:/Users/Anita\ Wray/Desktop/AwrayRockfish/scripts/Misc Scripts')
world <- ne_countries(scale = 10, returnclass = "sf")
#labels <- read_csv('maplabels.csv')
```

```{r maps, warning=FALSE, include=FALSE}
## Build a blank map for Washington/PS
map <- ggplot(data = world) +
  geom_sf() +
  coord_sf(ylim = c(50.410973, 46.025), xlim = c(-125.25, -122.180), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank()) +
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 47, to = 50, by = 1))

map

#Build one map with labels for multiplot
map_black <- ggplot(data = world) +
  geom_sf() +
  coord_sf(ylim = c(50.410973, 46.025), xlim = c(-126.25, -121.75), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = seq(from = -126, to = -121.75, by = 1)) +
  scale_y_continuous(breaks = seq(from = 46, to = 50, by = 1))

map2 <- ggplot(data = world) +
  geom_sf() +
  coord_sf(ylim = c(50.410973, 47.025), xlim = c(-125.25, -122.180), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 46, to = 50, by = 1))
```

```{r yellowtail, include=FALSE}
yellowtail <- read_csv('yellowtail_pie_map.csv', show_col_types = FALSE)
categories <- c("1", "2")
my_cols <- c('blue', 'red')

plot_yellowtail <- map_black + geom_scatterpie(data = yellowtail, 
                                aes(x=`long`, y=`lat`, 
                                         group = `region`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.7)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = my_cols)+
  geom_scatterpie_legend((yellowtail$radius), x = -125.57, y= 46.41, n = 2, 
                         labeller = function(x) x*10)

plot_yellowtail
```

```{r black, include=FALSE}
black <- read_csv('black_pie_map.csv', show_col_types = FALSE)
categories <- c("1", "2")
my_cols <- c('blue', 'red')

plot_black <- map_black + geom_scatterpie(data = black, 
                                aes(x=`long`, y=`lat`, 
                                         group = `region`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.7)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = my_cols)+
  geom_scatterpie_legend((black$radius), x = -125.57, y= 46.71, n = 2, 
                         labeller = function(x) x*40)

plot_black
```

```{r greenstriped, include=TRUE}
greenstriped <- read_csv('greenstriped_pie_map.csv', show_col_types = FALSE)
categories <- c("1", "2")
my_cols <- c('blue', 'red')

plot_greenstriped <- map_black + geom_scatterpie(data = greenstriped, 
                                aes(x=`long`, y=`lat`, 
                                         group = `region`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.7)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = my_cols)+
  geom_scatterpie_legend((greenstriped$radius), x = -125.57, y= 46.41, n = 2, 
                         labeller = function(x) x*17)+
  ggtitle('Greenstriped')+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),  #remove y axis ticks
        legend.position = 'none') +  
  annotation_scale(location = "tr", width_hint = 0.25)



plot_greenstriped
```

```{r redstripe, include=FALSE}
redstripe <- read_csv('redstripe_pie_map.csv', show_col_types = FALSE)
categories <- c("1", "2")
my_cols <- c('blue', 'red')

plot_redstripe <- map_black + geom_scatterpie(data = redstripe, 
                                aes(x=`long`, y=`lat`, 
                                         group = `region`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.7)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = my_cols)+
  geom_scatterpie_legend((greenstriped$radius), x = -125.57, y= 46.41, n = 2, 
                         labeller = function(x) x*20)

plot_redstripe
```

```{r pugetsound, include=FALSE}
pugetsound <- read_csv('pugetsound_pie_map.csv', show_col_types = FALSE)
categories <- c("1")
my_cols <- c('blue')

plot_pugetsound <- map_black + geom_scatterpie(data = pugetsound, 
                                aes(x=`long`, y=`lat`, 
                                         group = `region`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.7)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = my_cols)+
  geom_scatterpie_legend((pugetsound$radius), x = -125.57, y= 46.41, n = 2, 
                         labeller = function(x) x*10)

plot_pugetsound
```



```{r patchwork, echo=FALSE}

plot_black <- plot_black +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),  #remove y axis ticks
        legend.position = 'none',
        axis.title = element_text(size = 1)) +  
  annotation_scale(location = "tr", width_hint = 0.25)+
  ggtitle('Black')

plot_redstripe <- plot_redstripe +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),  #remove y axis ticks
        legend.position = 'none',
        axis.title = element_text(size = 1)) +  
  annotation_scale(location = "tr", width_hint = 0.25)+
  ggtitle('Redstripe')

plot_pugetsound <- plot_pugetsound +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),  #remove y axis ticks
        legend.position = 'none',
        axis.title = element_text(size = 1)) +  
  annotation_scale(location = "tr", width_hint = 0.25)+
  ggtitle('Puget Sound')

plot_yellowtail <- plot_yellowtail +
  ggtitle('Yellowtail')+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),  #remove y axis ticks
        legend.position = 'none') +  
  annotation_scale(location = "tr", width_hint = 0.25)

p1 <- plot_yellowtail + plot_greenstriped + plot_layout(ncol = 2)
p2 <- plot_black + plot_pugetsound + plot_layout(ncol = 2)
p3 <- plot_redstripe + plot_spacer() + plot_layout(ncol = 2)

p1a <- plot_yellowtail + plot_greenstriped + plot_black
p2a <- plot_pugetsound + plot_redstripe



plot1 <- p1/p2/p3

plot1


ggsave(file = "C:/Users/Anita Wray/Desktop/Figures for Pop Structure Manuscript/Fig_3_pie_map.jpg",
    width = 180, 
    units = 'mm',
    dpi = 600)
p1a/p2a
dev.off()



```



