---
title: "map building"
author: "Anita Wray"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("sf")
library("ggspatial")
library('viridis')
library('rnaturalearth')
library('patchwork')

world <- ne_countries(scale = "large", returnclass = "sf")
cols <- c("NPS" = "#31688e", "SPS" = "#03AC13", "WC" = "#fde725", 'BC' = "#440154FF")

barriers <- data.frame(id = 1:3,
                       lat_1 = c(48.225353, 48.30888201726048, 49.002066),
                       lon_1 = c(-122.766328, -123.56424164803133, -122.758979),
                       lat_2 = c(48.132969, 48.150221501649284, 49.002066),
                       lon_2 = c(-122.837687, -123.5539663929622, -123.816018))


#Organize and subset dataset
rockfish2 <- read_csv('rockfishsamplesmetadata.csv')

brown_data <- subset(rockfish2, SpeciesID == 'Brown Rockfish')
copper_data <- subset(rockfish2, SpeciesID == 'Copper Rockfish')
quillback_data <- subset(rockfish2, SpeciesID == 'Quillback Rockfish')
redstripe_data <- subset(rockfish2, SpeciesID == 'Redstripe Rockfish')
black_data <- subset(rockfish2, SpeciesID == 'Black Rockfish')
greenstriped_data <- subset(rockfish2, SpeciesID == 'Greenstriped Rockfish')
pugetsound_data <- subset(rockfish2, SpeciesID == 'Puget Sound Rockfish')
yellowtail_data <- subset(rockfish2, SpeciesID == 'Yellowtail Rockfish')

BCQ <- rbind(brown_data, copper_data, quillback_data)

CH2 <- rbind(redstripe_data, greenstriped_data, black_data, pugetsound_data, yellowtail_data)
```

```{r puget sound map, echo=FALSE, warning=FALSE}
theme_set(theme_bw())

library(ggplot2)
library(sp)#
library(gridExtra)
library(ggrepel)
locations <- read_csv('geolocations.csv')
labels <- read_csv('maplabels.csv')

map <- ggplot(data = world) +
    geom_sf() +
    #annotation_scale(location = "tr", width_hint = 0.5) +
    #annotation_north_arrow(location = "bl", which_north = "true", 
                        # height = unit(1, 'cm'), width = unit(1, 'cm'),
                        # style = north_arrow_fancy_orienteering) +
    xlab("Longitude") + ylab("Latitude") +
    coord_sf(ylim = c(51, 47.025), xlim = c(-126.4, -121.93), expand = FALSE)+ 
    theme(panel.background = element_rect(fill=NA, color="gray90"),
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank()) 

#map





withpoints <- map + geom_point(data=locations, aes(x=`Start_Longitude`,
                                                   y=`Start_Latitude`, 
                                                   color = `Location`, 
                                                   fill = `Location`),
                               pch=21, size=5) +
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  theme(legend.position = "none")+
  geom_text(data=locations, aes(x=`Start_Longitude`, y=`Start_Latitude`, 
                                label = `Location`), hjust=.52, vjust=-.8, 
            fontface='bold') +
  scale_color_manual(values = c("NPS" = "black", "SPS" = "black", 
                                "WC" = "black", "BC" = "black")) +
  scale_fill_manual(values = cols)+
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 47, to = 50, by = 1)) +
  geom_text(data = labels, aes(Y, X, label = Label), size = 3)+
  geom_segment(data = barriers,
               aes(x = lon_1, y = lat_1, xend = lon_2, yend = lat_2),
               color = 'red', size = 1.12, lineend = 'round',
               linetype = '11')

```

```{r puget sound map final, echo=FALSE}
without_dots<- map +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text = element_text(size = 7))+
  geom_text(data=locations, aes(x=`Start_Longitude`, y=`Start_Latitude`, label = `Location`), fontface='bold', size = 4) +
  scale_color_manual(values = c("NPS" = "black", "SPS" = "black", 
                                "WC" = "black", "BC" = "black")) +
  scale_fill_manual(values = cols) +
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 47, to = 50, by = 1)) +
  geom_text(aes(x = -122.6, y = 49.5),
            label = 'British Columbia', size = 2)+
  geom_text(aes(x=-123.725, y = 47.447),
            label = 'Washington', size = 2)+
  geom_segment(data = barriers,
               aes(x = lon_1, y = lat_1, xend = lon_2, yend = lat_2),
               color = 'red', size = 1.12, lineend = 'round',
               linetype = '11') 

final_ch2 <- without_dots +
  geom_text(aes(x =- 123.64, y = 48.52),
    color = "black", label = "VS", size = 2) +
  geom_text(aes(x = -122.14, y = 48.168),
            color = 'black', label = 'AI', size = 2) +
  geom_text(aes(x = -122.3, y = 48.68),
            color = 'black', label = 'SJI', size = 2) +
  geom_text(aes(x = -124.26, y = 48.366),
    color = "black", label = 'Strait of Juan de Fuca', size = 2, angle = 340)+
  geom_text(aes(x =  - 125.21, y= 49.29),
    color = "black", label = 'Vancouver Island', size = 2)+  
  geom_text(aes(x = -124.11, y = 49.46),
    color = "black", label = 'Strait of Georgia', size = 2, angle = 340)+
  geom_segment(aes(x= - 123.65, y= 48.48, xend=-123.58, yend=48.36), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.4)+
  geom_segment(aes(x= - 122.41, y= 48.68, xend=-122.8, yend=48.64), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.4)+
  geom_segment(aes(x= - 122.23, y= 48.168, xend=-122.74, yend=48.18), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.4)

final_ch2






```


```{r puget sound map 2, echo=FALSE, warning=FALSE}
inset <- ggplot(data = world) +
    geom_sf() +
    theme(panel.background = element_rect(fill=NA, color="gray90"),
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank()) + 
  coord_sf(
  ylim = c(25.45, 50.5),
  xlim = c(-105.7, -126),
  expand = FALSE) +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.ticks.length = unit(0, "pt"), #length of tick marks
        legend.position = "none",
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = unit(c(0,0,0,0),"mm")) +
  geom_rect(ymin = 46.025,
            ymax = 50.110973,
            xmin = -121.014160,
            xmax = -125.6,
            fill = NA,
            color = 'red',
            size = 0.8)

without_dots2 <- without_dots +
  geom_text(aes(x =- 122.12, y = 47.3),
    color = "black", label = "TN", size = 2.5) +
  geom_text(aes(x = -122.12, y = 48.168),
            color = 'black', label = 'WB', size = 2.5) +
  geom_text(aes(x = -122.28, y = 48.68),
            color = 'black', label = 'SJI', size = 2.5)+
  geom_text(aes(x =- 123.64, y = 48.525),
            color = "black", label = "VS", size = 2.5) +
  geom_text(aes(x = -122.12, y = 48.48),
            color = 'black', label = 'AI', size = 2.5) +
  geom_segment(aes(x= - 123.65, y= 48.48, xend=-123.58, yend=48.36), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.4)+ ##VS
  geom_segment(aes(x= - 122.41, y= 48.68, xend=-122.8, yend=48.64), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.35)+ #SJI
  geom_segment(aes(x= - 122.23, y= 48.48, xend=-122.7, yend=48.24), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.35)+ #AI
  geom_segment(aes(x= - 122.29, y= 48.168, xend=-122.5, yend=48.22), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.35)+ #WB
  geom_segment(aes(x= - 122.25, y= 47.3, xend=-122.5, yend=47.3), arrow = arrow(length=unit(.15, 'cm')),
               color='black', lwd=0.35) + #TACOMA
  theme(axis.text.x=element_text(angle=45, hjust=1))

plot <- without_dots2|inset 

#plot + plot_annotation(tag_levels = 'A')


library(cowplot)


gg_inset_map1 <- ggdraw() +
  draw_plot(without_dots2) +
  draw_plot(inset, x = 0.13, y = 0.637, width = 0.31, height = 0.34)




#map_ch2 <- ggdraw() +
#  draw_plot(final_ch2) +
#  draw_plot(inset, x = 0.75, y = 0.734, width = 0.21, height = 0.24)

#ggsave(filename = "C:/Users/Anita Wray/Desktop/Figures for Pop Structure Manuscript/Fig1-Map.jpg",
#    width = 80, 
#    height = 100, 
#    units = 'mm',
#    dpi = 600)
#map_ch2
#dev.off()

ggsave(file = "C:/Users/Anita Wray/Desktop/Figures for Hybrid Manuscript/Fig1-Map.jpg",
       width = 80, 
    height = 100, 
    units = 'mm',
    dpi = 600)
gg_inset_map1
dev.off()
  
```
