---
title: "pie_map_BCQ"
author: "Anita Wray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
## Load packages
library("tidyverse")
theme_set(theme_bw())
library("sf")
library("ggspatial")
library('viridis')
library('rnaturalearth')
library('diveRsity')
library('patchwork')
library('maps')
library(scatterpie)
knitr::opts_chunk$set(dev = "ragg_png")

## Set WD and subset data for species specific graphs
setwd('C:/Users/Anita\ Wray/Desktop/AwrayRockfish/scripts/Misc Scripts')
world <- ne_countries(scale = 10, returnclass = "sf")
labels <- read_csv('maplabels.csv')
```

```{r maps, warning=FALSE, include=FALSE}
## Build a blank map for Washington/PS
map <- ggplot(data = world) +
  geom_sf() +
  coord_sf(ylim = c(50.410973, 47.025), xlim = c(-125.25, -122.180), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank()) +
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 47, to = 50, by = 1)) +
  geom_text(data = labels, aes(Y, X, label = Label), size = 3.4)

map

#Build one map with labels for multiplot
map2 <- ggplot(data = world) +
  geom_sf() +
  coord_sf(ylim = c(50.410973, 47.025), xlim = c(-125.5, -122.180), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = seq(from = -126, to = -122, by = 1)) +
  scale_y_continuous(breaks = seq(from = 47, to = 50, by = 1)) +
  geom_text(data = labels, aes(Y, X, label = Label), size = 3.4)

#Build a map of US west coast for brown samples
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
#states <- cbind(states, st_coordinates(st_centroid(states)))
browncoastmap <- ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, fill = NA) + 
  coord_sf(ylim = c(49.5, 31), xlim = c(-125.6, -113.12), expand = FALSE)+ 
  theme(panel.background = element_rect(fill=NA, color="gray90"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = seq(from = -125, to = -115, by = 5)) +
  scale_y_continuous(breaks = seq(from = 30, to = 50, by = 5))
```

```{r quillback, echo=FALSE}
#Quillback
quillback <- read_csv('test1.csv', show_col_types = FALSE)
quillback <- quillback[1:14,1:6]
categories <- c("1", "2")
pal_ks <- wes_palette("Cavalcanti1", n = 3)
cols_k2 <- c('2' = pal_ks[2], '1' = pal_ks[1])
cols_k3 <- c('CG1' = pal_ks[2], 'CG3' = pal_ks[1], 'CG2' = pal_ks[3])

plot1 <- map2 + geom_scatterpie(data = quillback, 
                                aes(x=`long`, y=`lat`, r = `radius`),
                                color = NA,
                                legend_name = 'type', 
                                cols = categories,
                                alpha = 0.9)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = cols_k2)+
  geom_scatterpie_legend((quillback$radius), x = -125.17, y= 47.41, n = 3, 
                         labeller = function(x) x*40)

plot1
```

```{r brown, echo=FALSE}
#Brown
brown <- read_csv('brown_map_pie_k2.csv', show_col_types = FALSE)
brown_sound <- brown[1:10,]
brown_coast <- brown[10:11,]

my_cols_coast <- '#ff9900'

plot_brown <- map2 + geom_scatterpie(data = brown_sound, 
                                     aes(x=`long`, y=`lat`, r = `radius`),
                                     color = NA,
                                     legend_name = 'type', 
                                     cols = categories,
                                     alpha = 0.9)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = cols_k2)+
  geom_scatterpie_legend((brown_sound$radius), x = -125.17, y= 47.41, n =3,
                         labeller = function(x) x*30)


plot_brown_coast <- browncoastmap + geom_scatterpie(data = brown_coast, 
                                     aes(x=`long`, y=`lat`, r = `radius`),
                                     color = NA,
                                     legend_name = 'type', 
                                     cols = categories,
                                     alpha = 0.8)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = cols_k2) +
  geom_scatterpie_legend((brown_coast$radius), x = -124.3, y= 33.2, n =3,
                         labeller = function(x) x*4)

plot_brown + plot_brown_coast + plot_annotation(tag_levels = 'A')

```

```{r copper, echo=FALSE}
#Copper

copper <- read_csv('copper_map_pie.csv', show_col_types = FALSE)
categories_k3 <- c("CG1", "CG2", "CG3")
#cols_k3 <- c('CG1'='#3366cc', 'CG2'='#dc3912', 'CG3'='#ff9900')

plot_copper <- map2 + geom_scatterpie(data = copper, 
                                     aes(x=`long`, y=`lat`, 
                                          r = radius),
                                     color = NA,
                                     legend_name = 'type', 
                                     cols = categories_k3,
                                     alpha = 0.9)+
  theme(legend.position = 'none')+
  scale_fill_manual(values = cols_k3)+
  geom_scatterpie_legend((copper$radius), x = -125.05, y= 47.47, n =3,
                         labeller = function(x) x*50)

plot_copper
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
quillback <- plot1 + annotation_scale(location = "tr", width_hint = 0.25)
brown <- (plot_brown + 
  annotation_scale(location = "tr", width_hint = 0.25))+
  (plot_brown_coast+
  annotation_scale(location = "tr", width_hint = 0.25))
copper <- plot_copper + 
  annotation_scale(location = "tr", width_hint = 0.25)


quillback
copper
brown 
```

